---
- hosts: _Master
  
  tasks:

  - name: Update APT package manager repositories cache
    become: true
    apt:
      update_cache: yes
  - name: Install basic list of packages
    apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common', 'openjdk-8-jdk']
      state: present
      update_cache: yes

  - name: Ensure the jenkins apt repository key is installed
    become: true
    apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key 
      state: present

  - name: ensure the repository is configured
    become: true
    apt_repository: 
      repo: 'deb https://pkg.jenkins.io/debian-stable binary/' 
      state: present

  - name: ensure jenkins is installed
    become: true
    apt: 
        name: "jenkins" 
        update_cache: yes

  - name: "Starting jenkins"
    service:
        name: "jenkins"
        state: started
        enabled: yes
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg


  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install Docker packages
    apt:
      name: ['docker-ce','docker-ce-cli','containerd.io']
      state: present

  - name: Install Docker-compose
    become: yes
    #  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
      dest: /usr/local/bin/docker-compose
      mode: +x